config/routes.rb
Rails.application.routes.draw do
  get 'walk_of_life', to: "walk_of_lives#index"
  get 'hobbies', to: "hobbies#index"
  get 'projects', to: "projects#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'download_cv', to: "pages#download_cv"
  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cv.rb
class Cv < ApplicationRecord
end

app/models/hobby.rb
class Hobby < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/walk_of_life.rb
class WalkOfLife < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  # GET /hobbies or /hobbies.json
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def download_cv
    send_file "#{Rails.root}/app/assets/CVRASB.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/controllers/walk_of_lives_controller.rb
class WalkOfLivesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/walk_of_lives_helper.rb
module WalkOfLivesHelper
end

app/views/hobbies/index.html.erb
<h1>Hobbies</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "stylesheet.css" %>

  </head>

  <body>
    <nav class="navMenu">
      <a href="/">Rodrigo Borges</a>
      <a href="/projects">Portfolio</a>
      <a href="/walk_of_life">Walk of Life</a>
      <a href="/hobbies">Hobbies</a>
      <%= link_to "CV", download_cv_path, class: "download-cv" %>
      <div class="dot"></div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<p>Greetings, I am Rodrigo Borges and this is my Portfolio.</p>
<div><%= image_tag "main.jfif", class: "imageRounded" %></div>

app/views/projects/index.html.erb
<h1>Projects</h1>

app/views/walk_of_lives/_form.html.erb
<%= form_with(model: walk_of_life) do |form| %>
  <% if walk_of_life.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(walk_of_life.errors.count, "error") %> prohibited this walk_of_life from being saved:</h2>

      <ul>
        <% walk_of_life.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/walk_of_lives/_walk_of_life.html.erb
<div id="<%= dom_id walk_of_life %>">
</div>

app/views/walk_of_lives/edit.html.erb
<h1>Editing walk of life</h1>

<%= render "form", walk_of_life: @walk_of_life %>

<br>

<div>
  <%= link_to "Show this walk of life", @walk_of_life %> |
  <%= link_to "Back to walk of lives", walk_of_lives_path %>
</div>

app/views/walk_of_lives/index.html.erb
<h1>Walk of life</h1>

app/views/walk_of_lives/new.html.erb
<h1>New walk of life</h1>

<%= render "form", walk_of_life: @walk_of_life %>

<br>

<div>
  <%= link_to "Back to walk of lives", walk_of_lives_path %>
</div>

app/views/walk_of_lives/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @walk_of_life %>

<div>
  <%= link_to "Edit this walk of life", edit_walk_of_life_path(@walk_of_life) %> |
  <%= link_to "Back to walk of lives", walk_of_lives_path %>

  <%= button_to "Destroy this walk of life", @walk_of_life, method: :delete %>
</div>